# ============================================================================
# Maxwell's Wallet VM Module
# ============================================================================
# Creates VM(s) for hosting Maxwell's Wallet web application via cloudflared
# tunnel. Uses Ubuntu 24.04 VM template with Docker pre-installed.
#
# NOTE: Provider is configured in the calling environment (envs/prod),
# not here. The module just uses whatever provider the root module configures.

terraform {
  required_version = ">= 1.0"

  required_providers {
    proxmox = {
      source  = "Telmate/proxmox"
      version = "= 3.0.2-rc04"
    }
  }
}

# ============================================================================
# Maxwell's Wallet VMs
# ============================================================================

resource "proxmox_vm_qemu" "wallet" {
  for_each = var.instances

  # VM identification
  vmid        = each.value.vmid
  name        = each.key
  target_node = each.value.node

  # Clone from template (linked clone - requires shared storage like ceph)
  clone      = var.vm_template
  full_clone = false

  # VM settings
  onboot   = var.onboot
  vm_state = "running"
  agent    = 1
  scsihw   = "virtio-scsi-single"

  # Serial device for cloud-init output
  serial {
    id = 0
  }

  # Resources
  cores   = var.vm_cores
  sockets = 1
  memory  = var.vm_memory

  # Disk configuration
  disks {
    scsi {
      scsi0 {
        disk {
          size    = var.vm_disk_size
          storage = var.vm_storage
        }
      }
    }
    # Cloud-init drive - required for applying cloud-init settings
    ide {
      ide2 {
        cloudinit {
          storage = var.vm_storage
        }
      }
    }
  }

  # Network: eth0 - Transfer VLAN (external traffic via cloudflared)
  network {
    id     = 0
    model  = "virtio"
    bridge = var.vlans["transfer"].bridge
  }

  # Network: eth1 - Management VLAN (SSH, internal access)
  network {
    id     = 1
    model  = "virtio"
    bridge = var.vlans["mgmt"].bridge
  }

  # Cloud-init configuration
  os_type    = "cloud-init"
  ciuser     = var.cloud_init_user
  cipassword = var.cloud_init_password
  sshkeys    = var.ssh_public_key

  # Static IP configuration via cloud-init
  ipconfig0    = "ip=${each.value.transfer_ip}/24,gw=${var.vlans["transfer"].gateway}"
  ipconfig1    = "ip=${each.value.mgmt_ip}/24"
  nameserver   = var.dns_primary
  searchdomain = var.vlans["transfer"].domain

  # Tags for organization
  tags = join(",", compact([
    each.value.environment, # demo, beta
    "maxwells-wallet",
    var.env
  ]))

  lifecycle {
    ignore_changes = [
      # Prevent recreation on template changes
      clone,
      # Cloud-init changes don't require recreation
      ciuser,
      cipassword,
      sshkeys,
    ]
  }
}

# ============================================================================
# Outputs for Ansible Inventory
# ============================================================================

locals {
  hosts = {
    for name, inst in var.instances : name => {
      ansible_host   = "${name}.mgmt"   # SSH via DNS hostname
      transfer_ip    = inst.transfer_ip # For SWAG/cloudflared
      mgmt_ip        = inst.mgmt_ip
      dns_mgmt       = "${name}.mgmt"   # DNS name on mgmt network
      wallet_env     = inst.environment # Renamed from 'environment' (Ansible reserved word)
      domain         = inst.domain
      swag_subdomain = inst.environment # demo or beta
      image_tag      = inst.image_tag
      vmid           = inst.vmid
    }
  }

  ansible_inventory = {
    all = {
      children = {
        maxwells_wallet = { hosts = local.hosts }
      }
      vars = {
        ansible_user = var.cloud_init_user
      }
    }
  }
}

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory/${var.env}.yaml"
  content         = "---\n# Auto-generated by Terraform - do not edit\n${yamlencode(local.ansible_inventory)}"
  file_permission = "0644"
}
